### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by obiwankennedy** [Aluminium95/JdrScenar#6]
/usr/bin/ld: cannot open output file /home/XXX/application/other/JdrScenar-master/build/timeline: No such file or directory

Any clues ?

**Comment by Aluminium95** [comment]
I am sorry, but this code is:
- unmaintained for 2 years now ...
- very unstable and was never finished
- was experimental when it was written, but now uses a LOT of deprecated features of Clutter and the Gtk stack in general

I just forgot to remove this repository (among many others), sorry ...
